export enum InputAction {
	MOVE_UP = 'MOVE_UP',
	MOVE_DOWN = 'MOVE_DOWN',
	MOVE_LEFT = 'MOVE_LEFT',
	MOVE_RIGHT = 'MOVE_RIGHT',
	ATTACK = 'ATTACK',
	DODGE = 'DODGE',
	GUARD = 'GUARD',
	INTERACT = 'INTERACT',
	PAUSE = 'PAUSE',
	INVENTORY = 'INVENTORY',
}
